# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data/hyperlog.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data/hyperlog.proto',
  package='',
  serialized_pb='\n\x13\x64\x61ta/hyperlog.proto\"\x80\x01\n\x04Node\x12\x0e\n\x06\x63hange\x18\x01 \x02(\r\x12\x0b\n\x03key\x18\x02 \x02(\t\x12\x0b\n\x03log\x18\x03 \x02(\t\x12\x0b\n\x03seq\x18\x04 \x01(\r\x12\x10\n\x08identity\x18\x07 \x01(\x0c\x12\x11\n\tsignature\x18\x08 \x01(\x0c\x12\r\n\x05value\x18\x05 \x02(\x0c\x12\r\n\x05links\x18\x06 \x03(\t\"4\n\x05\x45ntry\x12\x0e\n\x06\x63hange\x18\x01 \x02(\r\x12\x0c\n\x04node\x18\x02 \x02(\t\x12\r\n\x05links\x18\x03 \x03(\t\"\x1f\n\x03Log\x12\x0b\n\x03log\x18\x01 \x02(\t\x12\x0b\n\x03seq\x18\x02 \x02(\r\"P\n\tHandshake\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x12\n\x04mode\x18\x02 \x01(\t:\x04sync\x12\x10\n\x08metadata\x18\x03 \x01(\x0c\x12\x0c\n\x04live\x18\x04 \x01(\x08')




_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='change', full_name='Node.change', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='Node.key', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log', full_name='Node.log', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='Node.seq', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='Node.identity', index=4,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Node.signature', index=5,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Node.value', index=6,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='links', full_name='Node.links', index=7,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=152,
)


_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='change', full_name='Entry.change', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node', full_name='Entry.node', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='links', full_name='Entry.links', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=154,
  serialized_end=206,
)


_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='Log.log', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='Log.seq', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=208,
  serialized_end=239,
)


_HANDSHAKE = _descriptor.Descriptor(
  name='Handshake',
  full_name='Handshake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Handshake.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='Handshake.mode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value="sync",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='Handshake.metadata', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='live', full_name='Handshake.live', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=241,
  serialized_end=321,
)

DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Entry'] = _ENTRY
DESCRIPTOR.message_types_by_name['Log'] = _LOG
DESCRIPTOR.message_types_by_name['Handshake'] = _HANDSHAKE

class Node(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _NODE

  # @@protoc_insertion_point(class_scope:Node)

class Entry(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _ENTRY

  # @@protoc_insertion_point(class_scope:Entry)

class Log(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _LOG

  # @@protoc_insertion_point(class_scope:Log)

class Handshake(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _HANDSHAKE

  # @@protoc_insertion_point(class_scope:Handshake)


# @@protoc_insertion_point(module_scope)
