#!/usr/bin/env python3
#
# pat-log
#

import os
import sys
from argparse import ArgumentParser

from logging import (
    debug,
    warning,
    error,
)
from pat import Pat


DESCRIPTION = '''View a log of recent changes.'''


def parse_args(argv):
    parser = ArgumentParser('pat-log', description=DESCRIPTION)
    parser.add_argument('path',
                        nargs='?',
                        help='path of the database',
                        default=os.getcwd())
    return parser.parse_args(argv)


def form(obj):

    data = {
        'version': obj['version'],
        'date': obj['date'],
        'puts': obj.get('puts', 0),
        'deletes': obj.get('deletes', 0),
    }

    message = ("Version: {version} [+{puts}, -{deletes}]\n"
               "Date: {date}").format(**data)

    if obj['message']:
        message = '%s\n\n   %s' % (message, obj['message'])
    return message


def main(argv):
    args = parse_args(argv)
    debug('pat-log %s' % args)

    try:
        pat = Pat(args.path)
    except Exception as err:
        print('Error opening pat:', err, file=sys.stderr)
        # error('Error opening pat {}', err)
        return 1

    messages = [form(change)
                for change in pat.changes()
                if not change['root']
                ]

    print('\n\n'.join(messages))
    return os.EX_OK

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
