#!/usr/bin/env python3
#
# pat-files
#

import os
import sys
from argparse import ArgumentParser

from logging import (
    debug,
    warning,
    error,
)
from pat import Pat


DESCRIPTION = '''Lists the files stored in the current repository'''


def parse_args(argv):
    parser = ArgumentParser('pat-files', description=DESCRIPTION)
    parser.add_argument('path',
                        default=os.getcwd(),
                        nargs='?',
                        help='path of the database')
    parser.add_argument('--limit',
                        type=int,
                        default=-1,
                        help='Max number of files to list')
    return parser.parse_args(argv)


def main(argv):
    args = parse_args(argv)
    debug('pat-files %s' % args)

    try:
        pat = Pat(args.path)
    except Exception as err:
        print('Error opening pat:', err, file=sys.stderr)
        # error('Error opening pat {}', err)
        return 1

    return os.EX_OK

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
